export enum BlogPostStatus {
  PUBLISHED = "PUBLISHED",
  DRAFT = "DRAFT",
  DELETE = "DELETE",
}

export enum BlogPostCategory {
  RECOMMENDED = "RECOMMENDED",
  NEWS = "NEWS",
  PRODUCT_GUIDE = "PRODUCT_GUIDE",
  REVIEWS = "REVIEWS",
  TECHNOLOGY = "TECHNOLOGY",
  HOW_TO = "HOW_TO",
  HUMOR = "HUMOR",
}
